server.port: 8888
app:
   name: spring-boot-config-application
   message: Hello From the Spring Boot Application ${app.name}
list:
    values: One, Two, Three
db.connection:
             connectionName: http://localhost:8090/db
             username: achu
             passowrd: pattnaik
             port: 7001

management.endpoints.web.exposure.include: "*"
spring:
  profiles:
    active: test